#--
# Copyright (C) 2007,2008 William N Dortch <bill.dortch@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#++
#


module Cheri
module AWT
module Constants
ConstRec = Cheri::Java::Builder::Constants::ConstRec
@constants = {}
class << self
  
  def add(y,t,d) #:nodoc:
    unless (@constants[y])
      @constants[y] = ConstRec.new(t,d)
      return
    end
    r = @constants[y]
    r = r.next_rec while r.next_rec
    r.next_rec = ConstRec.new(t,d)
  end

  # call-seq:
  #   Constants.get(symbol)             -> ConstRec or nil
  #   Constants.get_const_recs(symbol)  -> ConstRec or nil
  #   
  def get(y)
    @constants[y]
  end
  alias_method :get_const_recs, :get
  
end #self
byte = 'byte'
int = 'int'
char = 'char'
short = 'short'
long = 'long'
float = 'float'
integer = 'java.lang.Integer'
jfloat = 'java.lang.Float'
jbool = 'java.lang.Boolean'
string = 'java.lang.String'
object = 'java.lang.Object'

decl_cls = 'java.awt.image.ImageObserver'
add(:WIDTH,int,decl_cls)
add(:HEIGHT,int,decl_cls)
add(:PROPERTIES,int,decl_cls)
add(:SOMEBITS,int,decl_cls)
add(:FRAMEBITS,int,decl_cls)
add(:ALLBITS,int,decl_cls)
add(:ERROR,int,decl_cls)
add(:ABORT,int,decl_cls)
decl_cls = 'java.awt.AWTEvent'
add(:COMPONENT_EVENT_MASK,long,decl_cls)
add(:CONTAINER_EVENT_MASK,long,decl_cls)
add(:FOCUS_EVENT_MASK,long,decl_cls)
add(:KEY_EVENT_MASK,long,decl_cls)
add(:MOUSE_EVENT_MASK,long,decl_cls)
add(:MOUSE_MOTION_EVENT_MASK,long,decl_cls)
add(:WINDOW_EVENT_MASK,long,decl_cls)
add(:ACTION_EVENT_MASK,long,decl_cls)
add(:ADJUSTMENT_EVENT_MASK,long,decl_cls)
add(:ITEM_EVENT_MASK,long,decl_cls)
add(:TEXT_EVENT_MASK,long,decl_cls)
add(:INPUT_METHOD_EVENT_MASK,long,decl_cls)
add(:PAINT_EVENT_MASK,long,decl_cls)
add(:INVOCATION_EVENT_MASK,long,decl_cls)
add(:HIERARCHY_EVENT_MASK,long,decl_cls)
add(:HIERARCHY_BOUNDS_EVENT_MASK,long,decl_cls)
add(:MOUSE_WHEEL_EVENT_MASK,long,decl_cls)
add(:WINDOW_STATE_EVENT_MASK,long,decl_cls)
add(:WINDOW_FOCUS_EVENT_MASK,long,decl_cls)
decl_cls = 'java.awt.Component'
add(:TOP_ALIGNMENT,float,decl_cls)
add(:CENTER_ALIGNMENT,float,decl_cls)
add(:BOTTOM_ALIGNMENT,float,decl_cls)
add(:LEFT_ALIGNMENT,float,decl_cls)
add(:RIGHT_ALIGNMENT,float,decl_cls)
decl_cls = 'java.awt.AlphaComposite'
add(:CLEAR,int,decl_cls)
add(:SRC,int,decl_cls)
add(:DST,int,decl_cls)
add(:SRC_OVER,int,decl_cls)
add(:DST_OVER,int,decl_cls)
add(:SRC_IN,int,decl_cls)
add(:DST_IN,int,decl_cls)
add(:SRC_OUT,int,decl_cls)
add(:DST_OUT,int,decl_cls)
add(:SRC_ATOP,int,decl_cls)
add(:DST_ATOP,int,decl_cls)
add(:XOR,int,decl_cls)
add(:Clear,decl_cls,decl_cls)
add(:Src,decl_cls,decl_cls)
add(:Dst,decl_cls,decl_cls)
add(:SrcOver,decl_cls,decl_cls)
add(:DstOver,decl_cls,decl_cls)
add(:SrcIn,decl_cls,decl_cls)
add(:DstIn,decl_cls,decl_cls)
add(:SrcOut,decl_cls,decl_cls)
add(:DstOut,decl_cls,decl_cls)
add(:SrcAtop,decl_cls,decl_cls)
add(:DstAtop,decl_cls,decl_cls)
add(:Xor,decl_cls,decl_cls)
decl_cls = 'java.awt.Adjustable'
add(:HORIZONTAL,int,decl_cls)
add(:VERTICAL,int,decl_cls)
add(:NO_ORIENTATION,int,decl_cls)
decl_cls = 'java.awt.BasicStroke'
add(:JOIN_MITER,int,decl_cls)
add(:JOIN_ROUND,int,decl_cls)
add(:JOIN_BEVEL,int,decl_cls)
add(:CAP_BUTT,int,decl_cls)
add(:CAP_ROUND,int,decl_cls)
add(:CAP_SQUARE,int,decl_cls)
decl_cls = 'java.awt.BorderLayout'
add(:NORTH,string,decl_cls)
add(:SOUTH,string,decl_cls)
add(:EAST,string,decl_cls)
add(:WEST,string,decl_cls)
add(:CENTER,string,decl_cls)
add(:BEFORE_FIRST_LINE,string,decl_cls)
add(:AFTER_LAST_LINE,string,decl_cls)
add(:BEFORE_LINE_BEGINS,string,decl_cls)
add(:AFTER_LINE_ENDS,string,decl_cls)
add(:PAGE_START,string,decl_cls)
add(:PAGE_END,string,decl_cls)
add(:LINE_START,string,decl_cls)
add(:LINE_END,string,decl_cls)
decl_cls = 'java.awt.BufferCapabilities::FlipContents'
add(:UNDEFINED,'java.awt.BufferCapabilities$FlipContents',decl_cls)
add(:BACKGROUND,'java.awt.BufferCapabilities$FlipContents',decl_cls)
add(:PRIOR,'java.awt.BufferCapabilities$FlipContents',decl_cls)
add(:COPIED,'java.awt.BufferCapabilities$FlipContents',decl_cls)
decl_cls = 'java.awt.Color'
color = 'java.awt.Color'
add(:White,color,decl_cls)
add(:WHITE,color,decl_cls)
add(:LightGray,color,decl_cls)
add(:LIGHT_GRAY,color,decl_cls)
add(:Gray,color,decl_cls)
add(:GRAY,color,decl_cls)
add(:DarkGray,color,decl_cls)
add(:DARK_GRAY,color,decl_cls)
add(:Black,color,decl_cls)
add(:BLACK,color,decl_cls)
add(:Red,color,decl_cls)
add(:RED,color,decl_cls)
add(:Pink,color,decl_cls)
add(:PINK,color,decl_cls)
add(:Orange,color,decl_cls)
add(:ORANGE,color,decl_cls)
add(:Yellow,color,decl_cls)
add(:YELLOW,color,decl_cls)
add(:Green,color,decl_cls)
add(:GREEN,color,decl_cls)
add(:Magenta,color,decl_cls)
add(:MAGENTA,color,decl_cls)
add(:Cyan,color,decl_cls)
add(:CYAN,color,decl_cls)
add(:Blue,color,decl_cls)
add(:BLUE,color,decl_cls)
add(:OPAQUE,int,decl_cls)
add(:BITMASK,int,decl_cls)
add(:TRANSLUCENT,int,decl_cls)
decl_cls = 'java.awt.ComponentOrientation'
add(:LEFT_TO_RIGHT,decl_cls,decl_cls)
add(:RIGHT_TO_LEFT,decl_cls,decl_cls)
add(:UNKNOWN,decl_cls,decl_cls)
decl_cls = 'java.awt.Cursor'
add(:DEFAULT_CURSOR,int,decl_cls)
add(:CROSSHAIR_CURSOR,int,decl_cls)
add(:TEXT_CURSOR,int,decl_cls)
add(:WAIT_CURSOR,int,decl_cls)
add(:SW_RESIZE_CURSOR,int,decl_cls)
add(:SE_RESIZE_CURSOR,int,decl_cls)
add(:NW_RESIZE_CURSOR,int,decl_cls)
add(:NE_RESIZE_CURSOR,int,decl_cls)
add(:N_RESIZE_CURSOR,int,decl_cls)
add(:S_RESIZE_CURSOR,int,decl_cls)
add(:W_RESIZE_CURSOR,int,decl_cls)
add(:E_RESIZE_CURSOR,int,decl_cls)
add(:HAND_CURSOR,int,decl_cls)
add(:MOVE_CURSOR,int,decl_cls)
add(:CUSTOM_CURSOR,int,decl_cls)
decl_cls = 'java.awt.Dialog'
add(:DEFAULT_MODALITY_TYPE,'java.awt.Dialog$ModalityType',decl_cls)
decl_cls = 'java.awt.DisplayMode'
add(:BIT_DEPTH_MULTI,int,decl_cls)
add(:REFRESH_RATE_UNKNOWN,int,decl_cls)
decl_cls = 'java.awt.FileDialog'
add(:LOAD,int,decl_cls)
add(:SAVE,int,decl_cls)
decl_cls = 'java.awt.FlowLayout'
add(:LEFT,int,decl_cls)
add(:CENTER,int,decl_cls)
add(:RIGHT,int,decl_cls)
add(:LEADING,int,decl_cls)
add(:TRAILING,int,decl_cls)
decl_cls = 'java.awt.Font'
add(:DIALOG,string,decl_cls)
add(:DIALOG_INPUT,string,decl_cls)
add(:SANS_SERIF,string,decl_cls)
add(:SERIF,string,decl_cls)
add(:MONOSPACED,string,decl_cls)
add(:PLAIN,int,decl_cls)
add(:BOLD,int,decl_cls)
add(:ITALIC,int,decl_cls)
add(:ROMAN_BASELINE,int,decl_cls)
add(:CENTER_BASELINE,int,decl_cls)
add(:HANGING_BASELINE,int,decl_cls)
add(:TRUETYPE_FONT,int,decl_cls)
add(:TYPE1_FONT,int,decl_cls)
add(:LAYOUT_LEFT_TO_RIGHT,int,decl_cls)
add(:LAYOUT_RIGHT_TO_LEFT,int,decl_cls)
add(:LAYOUT_NO_START_CONTEXT,int,decl_cls)
add(:LAYOUT_NO_LIMIT_CONTEXT,int,decl_cls)
decl_cls = 'java.awt.Frame'
add(:NORMAL,int,decl_cls)
add(:ICONIFIED,int,decl_cls)
add(:MAXIMIZED_HORIZ,int,decl_cls)
add(:MAXIMIZED_VERT,int,decl_cls)
add(:MAXIMIZED_BOTH,int,decl_cls)
decl_cls = 'java.awt.GraphicsConfigTemplate'
add(:REQUIRED,int,decl_cls)
add(:PREFERRED,int,decl_cls)
add(:UNNECESSARY,int,decl_cls)
decl_cls = 'java.awt.GraphicsDevice'
add(:TYPE_RASTER_SCREEN,int,decl_cls)
add(:TYPE_PRINTER,int,decl_cls)
add(:TYPE_IMAGE_BUFFER,int,decl_cls)
decl_cls = 'java.awt.GridBagConstraints'
add(:RELATIVE,int,decl_cls)
add(:REMAINDER,int,decl_cls)
add(:NONE,int,decl_cls)
add(:BOTH,int,decl_cls)
add(:HORIZONTAL,int,decl_cls)
add(:VERTICAL,int,decl_cls)
add(:CENTER,int,decl_cls)
add(:NORTH,int,decl_cls)
add(:NORTHEAST,int,decl_cls)
add(:EAST,int,decl_cls)
add(:SOUTHEAST,int,decl_cls)
add(:SOUTH,int,decl_cls)
add(:SOUTHWEST,int,decl_cls)
add(:WEST,int,decl_cls)
add(:NORTHWEST,int,decl_cls)
add(:PAGE_START,int,decl_cls)
add(:PAGE_END,int,decl_cls)
add(:LINE_START,int,decl_cls)
add(:LINE_END,int,decl_cls)
add(:FIRST_LINE_START,int,decl_cls)
add(:FIRST_LINE_END,int,decl_cls)
add(:LAST_LINE_START,int,decl_cls)
add(:LAST_LINE_END,int,decl_cls)
add(:BASELINE,int,decl_cls)
add(:BASELINE_LEADING,int,decl_cls)
add(:BASELINE_TRAILING,int,decl_cls)
add(:ABOVE_BASELINE,int,decl_cls)
add(:ABOVE_BASELINE_LEADING,int,decl_cls)
add(:ABOVE_BASELINE_TRAILING,int,decl_cls)
add(:BELOW_BASELINE,int,decl_cls)
add(:BELOW_BASELINE_LEADING,int,decl_cls)
add(:BELOW_BASELINE_TRAILING,int,decl_cls)
decl_cls = 'java.awt.Image'
add(:UndefinedProperty,object,decl_cls)
add(:SCALE_DEFAULT,int,decl_cls)
add(:SCALE_FAST,int,decl_cls)
add(:SCALE_SMOOTH,int,decl_cls)
add(:SCALE_REPLICATE,int,decl_cls)
add(:SCALE_AREA_AVERAGING,int,decl_cls)
decl_cls = 'java.awt.KeyboardFocusManager'
add(:FORWARD_TRAVERSAL_KEYS,int,decl_cls)
add(:BACKWARD_TRAVERSAL_KEYS,int,decl_cls)
add(:UP_CYCLE_TRAVERSAL_KEYS,int,decl_cls)
add(:DOWN_CYCLE_TRAVERSAL_KEYS,int,decl_cls)
decl_cls = 'java.awt.Label'
add(:LEFT,int,decl_cls)
add(:CENTER,int,decl_cls)
add(:RIGHT,int,decl_cls)
decl_cls = 'java.awt.MediaTracker'
add(:LOADING,int,decl_cls)
add(:ABORTED,int,decl_cls)
add(:ERRORED,int,decl_cls)
add(:COMPLETE,int,decl_cls)
decl_cls = 'java.awt.RenderingHints'
add(:KEY_ANTIALIASING,'java.awt.RenderingHints$Key',decl_cls)
add(:VALUE_ANTIALIAS_ON,object,decl_cls)
add(:VALUE_ANTIALIAS_OFF,object,decl_cls)
add(:VALUE_ANTIALIAS_DEFAULT,object,decl_cls)
add(:KEY_RENDERING,'java.awt.RenderingHints$Key',decl_cls)
add(:VALUE_RENDER_SPEED,object,decl_cls)
add(:VALUE_RENDER_QUALITY,object,decl_cls)
add(:VALUE_RENDER_DEFAULT,object,decl_cls)
add(:KEY_DITHERING,'java.awt.RenderingHints$Key',decl_cls)
add(:VALUE_DITHER_DISABLE,object,decl_cls)
add(:VALUE_DITHER_ENABLE,object,decl_cls)
add(:VALUE_DITHER_DEFAULT,object,decl_cls)
add(:KEY_TEXT_ANTIALIASING,'java.awt.RenderingHints$Key',decl_cls)
add(:VALUE_TEXT_ANTIALIAS_ON,object,decl_cls)
add(:VALUE_TEXT_ANTIALIAS_OFF,object,decl_cls)
add(:VALUE_TEXT_ANTIALIAS_DEFAULT,object,decl_cls)
add(:VALUE_TEXT_ANTIALIAS_GASP,object,decl_cls)
add(:VALUE_TEXT_ANTIALIAS_LCD_HRGB,object,decl_cls)
add(:VALUE_TEXT_ANTIALIAS_LCD_HBGR,object,decl_cls)
add(:VALUE_TEXT_ANTIALIAS_LCD_VRGB,object,decl_cls)
add(:VALUE_TEXT_ANTIALIAS_LCD_VBGR,object,decl_cls)
add(:KEY_TEXT_LCD_CONTRAST,'java.awt.RenderingHints$Key',decl_cls)
add(:KEY_FRACTIONALMETRICS,'java.awt.RenderingHints$Key',decl_cls)
add(:VALUE_FRACTIONALMETRICS_OFF,object,decl_cls)
add(:VALUE_FRACTIONALMETRICS_ON,object,decl_cls)
add(:VALUE_FRACTIONALMETRICS_DEFAULT,object,decl_cls)
add(:KEY_INTERPOLATION,'java.awt.RenderingHints$Key',decl_cls)
add(:VALUE_INTERPOLATION_NEAREST_NEIGHBOR,object,decl_cls)
add(:VALUE_INTERPOLATION_BILINEAR,object,decl_cls)
add(:VALUE_INTERPOLATION_BICUBIC,object,decl_cls)
add(:KEY_ALPHA_INTERPOLATION,'java.awt.RenderingHints$Key',decl_cls)
add(:VALUE_ALPHA_INTERPOLATION_SPEED,object,decl_cls)
add(:VALUE_ALPHA_INTERPOLATION_QUALITY,object,decl_cls)
add(:VALUE_ALPHA_INTERPOLATION_DEFAULT,object,decl_cls)
add(:KEY_COLOR_RENDERING,'java.awt.RenderingHints$Key',decl_cls)
add(:VALUE_COLOR_RENDER_SPEED,object,decl_cls)
add(:VALUE_COLOR_RENDER_QUALITY,object,decl_cls)
add(:VALUE_COLOR_RENDER_DEFAULT,object,decl_cls)
add(:KEY_STROKE_CONTROL,'java.awt.RenderingHints$Key',decl_cls)
add(:VALUE_STROKE_DEFAULT,object,decl_cls)
add(:VALUE_STROKE_NORMALIZE,object,decl_cls)
add(:VALUE_STROKE_PURE,object,decl_cls)
decl_cls = 'java.awt.Scrollbar'
add(:HORIZONTAL,int,decl_cls)
add(:VERTICAL,int,decl_cls)
decl_cls = 'java.awt.ScrollPane'
add(:SCROLLBARS_AS_NEEDED,int,decl_cls)
add(:SCROLLBARS_ALWAYS,int,decl_cls)
add(:SCROLLBARS_NEVER,int,decl_cls)
decl_cls = 'java.awt.SystemColor'
add(:DESKTOP,int,decl_cls)
add(:ACTIVE_CAPTION,int,decl_cls)
add(:ACTIVE_CAPTION_TEXT,int,decl_cls)
add(:ACTIVE_CAPTION_BORDER,int,decl_cls)
add(:INACTIVE_CAPTION,int,decl_cls)
add(:INACTIVE_CAPTION_TEXT,int,decl_cls)
add(:INACTIVE_CAPTION_BORDER,int,decl_cls)
add(:WINDOW,int,decl_cls)
add(:WINDOW_BORDER,int,decl_cls)
add(:WINDOW_TEXT,int,decl_cls)
add(:MENU,int,decl_cls)
add(:MENU_TEXT,int,decl_cls)
add(:TEXT,int,decl_cls)
add(:TEXT_TEXT,int,decl_cls)
add(:TEXT_HIGHLIGHT,int,decl_cls)
add(:TEXT_HIGHLIGHT_TEXT,int,decl_cls)
add(:TEXT_INACTIVE_TEXT,int,decl_cls)
add(:CONTROL,int,decl_cls)
add(:CONTROL_TEXT,int,decl_cls)
add(:CONTROL_HIGHLIGHT,int,decl_cls)
add(:CONTROL_LT_HIGHLIGHT,int,decl_cls)
add(:CONTROL_SHADOW,int,decl_cls)
add(:CONTROL_DK_SHADOW,int,decl_cls)
add(:SCROLLBAR,int,decl_cls)
add(:INFO,int,decl_cls)
add(:INFO_TEXT,int,decl_cls)
add(:NUM_COLORS,int,decl_cls)
add(:Desktop,'java.awt.SystemColor',decl_cls)
add(:ActiveCaption,'java.awt.SystemColor',decl_cls)
add(:ActiveCaptionText,'java.awt.SystemColor',decl_cls)
add(:ActiveCaptionBorder,'java.awt.SystemColor',decl_cls)
add(:InactiveCaption,'java.awt.SystemColor',decl_cls)
add(:InactiveCaptionText,'java.awt.SystemColor',decl_cls)
add(:InactiveCaptionBorder,'java.awt.SystemColor',decl_cls)
add(:Window,'java.awt.SystemColor',decl_cls)
add(:WindowBorder,'java.awt.SystemColor',decl_cls)
add(:WindowText,'java.awt.SystemColor',decl_cls)
add(:Menu,'java.awt.SystemColor',decl_cls)
add(:MenuText,'java.awt.SystemColor',decl_cls)
add(:Text,'java.awt.SystemColor',decl_cls)
add(:TextText,'java.awt.SystemColor',decl_cls)
add(:TextHighlight,'java.awt.SystemColor',decl_cls)
add(:TextHighlightText,'java.awt.SystemColor',decl_cls)
add(:TextInactiveText,'java.awt.SystemColor',decl_cls)
add(:Control,'java.awt.SystemColor',decl_cls)
add(:ControlText,'java.awt.SystemColor',decl_cls)
add(:ControlHighlight,'java.awt.SystemColor',decl_cls)
add(:ControlLtHighlight,'java.awt.SystemColor',decl_cls)
add(:ControlShadow,'java.awt.SystemColor',decl_cls)
add(:ControlDkShadow,'java.awt.SystemColor',decl_cls)
add(:Scrollbar,'java.awt.SystemColor',decl_cls)
add(:Info,'java.awt.SystemColor',decl_cls)
add(:InfoText,'java.awt.SystemColor',decl_cls)
decl_cls = 'java.awt.TextArea'
add(:SCROLLBARS_BOTH,int,decl_cls)
add(:SCROLLBARS_VERTICAL_ONLY,int,decl_cls)
add(:SCROLLBARS_HORIZONTAL_ONLY,int,decl_cls)
add(:SCROLLBARS_NONE,int,decl_cls)
decl_cls = 'java.awt.Transparency'
add(:OPAQUE,int,decl_cls)
add(:BITMASK,int,decl_cls)
add(:TRANSLUCENT,int,decl_cls)
decl_cls = 'java.awt.color.ColorSpace'
add(:TYPE_XYZ,int,decl_cls)
add(:TYPE_Lab,int,decl_cls)
add(:TYPE_Luv,int,decl_cls)
add(:TYPE_YCbCr,int,decl_cls)
add(:TYPE_Yxy,int,decl_cls)
add(:TYPE_RGB,int,decl_cls)
add(:TYPE_GRAY,int,decl_cls)
add(:TYPE_HSV,int,decl_cls)
add(:TYPE_HLS,int,decl_cls)
add(:TYPE_CMYK,int,decl_cls)
add(:TYPE_CMY,int,decl_cls)
add(:TYPE_2CLR,int,decl_cls)
add(:TYPE_3CLR,int,decl_cls)
add(:TYPE_4CLR,int,decl_cls)
add(:TYPE_5CLR,int,decl_cls)
add(:TYPE_6CLR,int,decl_cls)
add(:TYPE_7CLR,int,decl_cls)
add(:TYPE_8CLR,int,decl_cls)
add(:TYPE_9CLR,int,decl_cls)
add(:TYPE_ACLR,int,decl_cls)
add(:TYPE_BCLR,int,decl_cls)
add(:TYPE_CCLR,int,decl_cls)
add(:TYPE_DCLR,int,decl_cls)
add(:TYPE_ECLR,int,decl_cls)
add(:TYPE_FCLR,int,decl_cls)
add(:CS_sRGB,int,decl_cls)
add(:CS_LINEAR_RGB,int,decl_cls)
add(:CS_CIEXYZ,int,decl_cls)
add(:CS_PYCC,int,decl_cls)
add(:CS_GRAY,int,decl_cls)
decl_cls = 'java.awt.datatransfer.DataFlavor'
add(:StringFlavor,decl_cls,decl_cls)
add(:ImageFlavor,decl_cls,decl_cls)
add(:PlainTextFlavor,decl_cls,decl_cls)
add(:JavaSerializedObjectMimeType,string,decl_cls)
add(:JavaFileListFlavor,decl_cls,decl_cls)
add(:JavaJVMLocalObjectMimeType,string,decl_cls)
add(:JavaRemoteObjectMimeType,string,decl_cls)
decl_cls = 'java.awt.dnd.DnDConstants'
add(:ACTION_NONE,int,decl_cls)
add(:ACTION_COPY,int,decl_cls)
add(:ACTION_MOVE,int,decl_cls)
add(:ACTION_COPY_OR_MOVE,int,decl_cls)
add(:ACTION_LINK,int,decl_cls)
add(:ACTION_REFERENCE,int,decl_cls)
decl_cls = 'java.awt.dnd.DragSource'
cursor = 'java.awt.Cursor'
add(:DefaultCopyDrop,cursor,decl_cls)
add(:DefaultMoveDrop,cursor,decl_cls)
add(:DefaultLinkDrop,cursor,decl_cls)
add(:DefaultCopyNoDrop,cursor,decl_cls)
add(:DefaultMoveNoDrop,cursor,decl_cls)
add(:DefaultLinkNoDrop,cursor,decl_cls)
decl_cls = 'java.awt.event.ActionEvent'
add(:SHIFT_MASK,int,decl_cls)
add(:CTRL_MASK,int,decl_cls)
add(:META_MASK,int,decl_cls)
add(:ALT_MASK,int,decl_cls)
add(:ACTION_FIRST,int,decl_cls)
add(:ACTION_LAST,int,decl_cls)
add(:ACTION_PERFORMED,int,decl_cls)
decl_cls = 'java.awt.event.AdjustmentEvent'
add(:ADJUSTMENT_FIRST,int,decl_cls)
add(:ADJUSTMENT_LAST,int,decl_cls)
add(:ADJUSTMENT_VALUE_CHANGED,int,decl_cls)
add(:UNIT_INCREMENT,int,decl_cls)
add(:UNIT_DECREMENT,int,decl_cls)
add(:BLOCK_DECREMENT,int,decl_cls)
add(:BLOCK_INCREMENT,int,decl_cls)
add(:TRACK,int,decl_cls)
decl_cls = 'java.awt.event.ComponentEvent'
add(:COMPONENT_FIRST,int,decl_cls)
add(:COMPONENT_LAST,int,decl_cls)
add(:COMPONENT_MOVED,int,decl_cls)
add(:COMPONENT_RESIZED,int,decl_cls)
add(:COMPONENT_SHOWN,int,decl_cls)
add(:COMPONENT_HIDDEN,int,decl_cls)
add(:COMPONENT_EVENT_MASK,long,decl_cls)
decl_cls = 'java.awt.event.ContainerEvent'
add(:CONTAINER_FIRST,int,decl_cls)
add(:CONTAINER_LAST,int,decl_cls)
add(:COMPONENT_ADDED,int,decl_cls)
add(:COMPONENT_REMOVED,int,decl_cls)
decl_cls = 'java.awt.event.FocusEvent'
add(:FOCUS_FIRST,int,decl_cls)
add(:FOCUS_LAST,int,decl_cls)
add(:FOCUS_GAINED,int,decl_cls)
add(:FOCUS_LOST,int,decl_cls)
decl_cls = 'java.awt.event.HierarchyEvent'
add(:HIERARCHY_FIRST,int,decl_cls)
add(:HIERARCHY_CHANGED,int,decl_cls)
add(:ANCESTOR_MOVED,int,decl_cls)
add(:ANCESTOR_RESIZED,int,decl_cls)
add(:HIERARCHY_LAST,int,decl_cls)
add(:PARENT_CHANGED,int,decl_cls)
add(:DISPLAYABILITY_CHANGED,int,decl_cls)
add(:SHOWING_CHANGED,int,decl_cls)
decl_cls = 'java.awt.event.InputEvent'
add(:SHIFT_MASK,int,decl_cls)
add(:CTRL_MASK,int,decl_cls)
add(:META_MASK,int,decl_cls)
add(:ALT_MASK,int,decl_cls)
add(:ALT_GRAPH_MASK,int,decl_cls)
add(:BUTTON1_MASK,int,decl_cls)
add(:BUTTON2_MASK,int,decl_cls)
add(:BUTTON3_MASK,int,decl_cls)
add(:SHIFT_DOWN_MASK,int,decl_cls)
add(:CTRL_DOWN_MASK,int,decl_cls)
add(:META_DOWN_MASK,int,decl_cls)
add(:ALT_DOWN_MASK,int,decl_cls)
add(:BUTTON1_DOWN_MASK,int,decl_cls)
add(:BUTTON2_DOWN_MASK,int,decl_cls)
add(:BUTTON3_DOWN_MASK,int,decl_cls)
add(:ALT_GRAPH_DOWN_MASK,int,decl_cls)
decl_cls = 'java.awt.event.InputMethodEvent'
add(:INPUT_METHOD_FIRST,int,decl_cls)
add(:INPUT_METHOD_TEXT_CHANGED,int,decl_cls)
add(:CARET_POSITION_CHANGED,int,decl_cls)
add(:INPUT_METHOD_LAST,int,decl_cls)
decl_cls = 'java.awt.event.InvocationEvent'
add(:INVOCATION_FIRST,int,decl_cls)
add(:INVOCATION_DEFAULT,int,decl_cls)
add(:INVOCATION_LAST,int,decl_cls)
decl_cls = 'java.awt.event.ItemEvent'
add(:ITEM_FIRST,int,decl_cls)
add(:ITEM_LAST,int,decl_cls)
add(:ITEM_STATE_CHANGED,int,decl_cls)
add(:SELECTED,int,decl_cls)
add(:DESELECTED,int,decl_cls)
decl_cls = 'java.awt.event.KeyEvent'
add(:KEY_FIRST,int,decl_cls)
add(:KEY_LAST,int,decl_cls)
add(:KEY_TYPED,int,decl_cls)
add(:KEY_PRESSED,int,decl_cls)
add(:KEY_RELEASED,int,decl_cls)
add(:VK_ENTER,int,decl_cls)
add(:VK_BACK_SPACE,int,decl_cls)
add(:VK_TAB,int,decl_cls)
add(:VK_CANCEL,int,decl_cls)
add(:VK_CLEAR,int,decl_cls)
add(:VK_SHIFT,int,decl_cls)
add(:VK_CONTROL,int,decl_cls)
add(:VK_ALT,int,decl_cls)
add(:VK_PAUSE,int,decl_cls)
add(:VK_CAPS_LOCK,int,decl_cls)
add(:VK_ESCAPE,int,decl_cls)
add(:VK_SPACE,int,decl_cls)
add(:VK_PAGE_UP,int,decl_cls)
add(:VK_PAGE_DOWN,int,decl_cls)
add(:VK_END,int,decl_cls)
add(:VK_HOME,int,decl_cls)
add(:VK_LEFT,int,decl_cls)
add(:VK_UP,int,decl_cls)
add(:VK_RIGHT,int,decl_cls)
add(:VK_DOWN,int,decl_cls)
add(:VK_COMMA,int,decl_cls)
add(:VK_MINUS,int,decl_cls)
add(:VK_PERIOD,int,decl_cls)
add(:VK_SLASH,int,decl_cls)
add(:VK_0,int,decl_cls)
add(:VK_1,int,decl_cls)
add(:VK_2,int,decl_cls)
add(:VK_3,int,decl_cls)
add(:VK_4,int,decl_cls)
add(:VK_5,int,decl_cls)
add(:VK_6,int,decl_cls)
add(:VK_7,int,decl_cls)
add(:VK_8,int,decl_cls)
add(:VK_9,int,decl_cls)
add(:VK_SEMICOLON,int,decl_cls)
add(:VK_EQUALS,int,decl_cls)
add(:VK_A,int,decl_cls)
add(:VK_B,int,decl_cls)
add(:VK_C,int,decl_cls)
add(:VK_D,int,decl_cls)
add(:VK_E,int,decl_cls)
add(:VK_F,int,decl_cls)
add(:VK_G,int,decl_cls)
add(:VK_H,int,decl_cls)
add(:VK_I,int,decl_cls)
add(:VK_J,int,decl_cls)
add(:VK_K,int,decl_cls)
add(:VK_L,int,decl_cls)
add(:VK_M,int,decl_cls)
add(:VK_N,int,decl_cls)
add(:VK_O,int,decl_cls)
add(:VK_P,int,decl_cls)
add(:VK_Q,int,decl_cls)
add(:VK_R,int,decl_cls)
add(:VK_S,int,decl_cls)
add(:VK_T,int,decl_cls)
add(:VK_U,int,decl_cls)
add(:VK_V,int,decl_cls)
add(:VK_W,int,decl_cls)
add(:VK_X,int,decl_cls)
add(:VK_Y,int,decl_cls)
add(:VK_Z,int,decl_cls)
add(:VK_OPEN_BRACKET,int,decl_cls)
add(:VK_BACK_SLASH,int,decl_cls)
add(:VK_CLOSE_BRACKET,int,decl_cls)
add(:VK_NUMPAD0,int,decl_cls)
add(:VK_NUMPAD1,int,decl_cls)
add(:VK_NUMPAD2,int,decl_cls)
add(:VK_NUMPAD3,int,decl_cls)
add(:VK_NUMPAD4,int,decl_cls)
add(:VK_NUMPAD5,int,decl_cls)
add(:VK_NUMPAD6,int,decl_cls)
add(:VK_NUMPAD7,int,decl_cls)
add(:VK_NUMPAD8,int,decl_cls)
add(:VK_NUMPAD9,int,decl_cls)
add(:VK_MULTIPLY,int,decl_cls)
add(:VK_ADD,int,decl_cls)
add(:VK_SEPARATER,int,decl_cls)
add(:VK_SEPARATOR,int,decl_cls)
add(:VK_SUBTRACT,int,decl_cls)
add(:VK_DECIMAL,int,decl_cls)
add(:VK_DIVIDE,int,decl_cls)
add(:VK_DELETE,int,decl_cls)
add(:VK_NUM_LOCK,int,decl_cls)
add(:VK_SCROLL_LOCK,int,decl_cls)
add(:VK_F1,int,decl_cls)
add(:VK_F2,int,decl_cls)
add(:VK_F3,int,decl_cls)
add(:VK_F4,int,decl_cls)
add(:VK_F5,int,decl_cls)
add(:VK_F6,int,decl_cls)
add(:VK_F7,int,decl_cls)
add(:VK_F8,int,decl_cls)
add(:VK_F9,int,decl_cls)
add(:VK_F10,int,decl_cls)
add(:VK_F11,int,decl_cls)
add(:VK_F12,int,decl_cls)
add(:VK_F13,int,decl_cls)
add(:VK_F14,int,decl_cls)
add(:VK_F15,int,decl_cls)
add(:VK_F16,int,decl_cls)
add(:VK_F17,int,decl_cls)
add(:VK_F18,int,decl_cls)
add(:VK_F19,int,decl_cls)
add(:VK_F20,int,decl_cls)
add(:VK_F21,int,decl_cls)
add(:VK_F22,int,decl_cls)
add(:VK_F23,int,decl_cls)
add(:VK_F24,int,decl_cls)
add(:VK_PRINTSCREEN,int,decl_cls)
add(:VK_INSERT,int,decl_cls)
add(:VK_HELP,int,decl_cls)
add(:VK_META,int,decl_cls)
add(:VK_BACK_QUOTE,int,decl_cls)
add(:VK_QUOTE,int,decl_cls)
add(:VK_KP_UP,int,decl_cls)
add(:VK_KP_DOWN,int,decl_cls)
add(:VK_KP_LEFT,int,decl_cls)
add(:VK_KP_RIGHT,int,decl_cls)
add(:VK_DEAD_GRAVE,int,decl_cls)
add(:VK_DEAD_ACUTE,int,decl_cls)
add(:VK_DEAD_CIRCUMFLEX,int,decl_cls)
add(:VK_DEAD_TILDE,int,decl_cls)
add(:VK_DEAD_MACRON,int,decl_cls)
add(:VK_DEAD_BREVE,int,decl_cls)
add(:VK_DEAD_ABOVEDOT,int,decl_cls)
add(:VK_DEAD_DIAERESIS,int,decl_cls)
add(:VK_DEAD_ABOVERING,int,decl_cls)
add(:VK_DEAD_DOUBLEACUTE,int,decl_cls)
add(:VK_DEAD_CARON,int,decl_cls)
add(:VK_DEAD_CEDILLA,int,decl_cls)
add(:VK_DEAD_OGONEK,int,decl_cls)
add(:VK_DEAD_IOTA,int,decl_cls)
add(:VK_DEAD_VOICED_SOUND,int,decl_cls)
add(:VK_DEAD_SEMIVOICED_SOUND,int,decl_cls)
add(:VK_AMPERSAND,int,decl_cls)
add(:VK_ASTERISK,int,decl_cls)
add(:VK_QUOTEDBL,int,decl_cls)
add(:VK_LESS,int,decl_cls)
add(:VK_GREATER,int,decl_cls)
add(:VK_BRACELEFT,int,decl_cls)
add(:VK_BRACERIGHT,int,decl_cls)
add(:VK_AT,int,decl_cls)
add(:VK_COLON,int,decl_cls)
add(:VK_CIRCUMFLEX,int,decl_cls)
add(:VK_DOLLAR,int,decl_cls)
add(:VK_EURO_SIGN,int,decl_cls)
add(:VK_EXCLAMATION_MARK,int,decl_cls)
add(:VK_INVERTED_EXCLAMATION_MARK,int,decl_cls)
add(:VK_LEFT_PARENTHESIS,int,decl_cls)
add(:VK_NUMBER_SIGN,int,decl_cls)
add(:VK_PLUS,int,decl_cls)
add(:VK_RIGHT_PARENTHESIS,int,decl_cls)
add(:VK_UNDERSCORE,int,decl_cls)
add(:VK_WINDOWS,int,decl_cls)
add(:VK_CONTEXT_MENU,int,decl_cls)
add(:VK_FINAL,int,decl_cls)
add(:VK_CONVERT,int,decl_cls)
add(:VK_NONCONVERT,int,decl_cls)
add(:VK_ACCEPT,int,decl_cls)
add(:VK_MODECHANGE,int,decl_cls)
add(:VK_KANA,int,decl_cls)
add(:VK_KANJI,int,decl_cls)
add(:VK_ALPHANUMERIC,int,decl_cls)
add(:VK_KATAKANA,int,decl_cls)
add(:VK_HIRAGANA,int,decl_cls)
add(:VK_FULL_WIDTH,int,decl_cls)
add(:VK_HALF_WIDTH,int,decl_cls)
add(:VK_ROMAN_CHARACTERS,int,decl_cls)
add(:VK_ALL_CANDIDATES,int,decl_cls)
add(:VK_PREVIOUS_CANDIDATE,int,decl_cls)
add(:VK_CODE_INPUT,int,decl_cls)
add(:VK_JAPANESE_KATAKANA,int,decl_cls)
add(:VK_JAPANESE_HIRAGANA,int,decl_cls)
add(:VK_JAPANESE_ROMAN,int,decl_cls)
add(:VK_KANA_LOCK,int,decl_cls)
add(:VK_INPUT_METHOD_ON_OFF,int,decl_cls)
add(:VK_CUT,int,decl_cls)
add(:VK_COPY,int,decl_cls)
add(:VK_PASTE,int,decl_cls)
add(:VK_UNDO,int,decl_cls)
add(:VK_AGAIN,int,decl_cls)
add(:VK_FIND,int,decl_cls)
add(:VK_PROPS,int,decl_cls)
add(:VK_STOP,int,decl_cls)
add(:VK_COMPOSE,int,decl_cls)
add(:VK_ALT_GRAPH,int,decl_cls)
add(:VK_BEGIN,int,decl_cls)
add(:VK_UNDEFINED,int,decl_cls)
add(:CHAR_UNDEFINED,char,decl_cls)
add(:KEY_LOCATION_UNKNOWN,int,decl_cls)
add(:KEY_LOCATION_STANDARD,int,decl_cls)
add(:KEY_LOCATION_LEFT,int,decl_cls)
add(:KEY_LOCATION_RIGHT,int,decl_cls)
add(:KEY_LOCATION_NUMPAD,int,decl_cls)
decl_cls = 'java.awt.event.MouseEvent'
add(:MOUSE_FIRST,int,decl_cls)
add(:MOUSE_LAST,int,decl_cls)
add(:MOUSE_CLICKED,int,decl_cls)
add(:MOUSE_PRESSED,int,decl_cls)
add(:MOUSE_RELEASED,int,decl_cls)
add(:MOUSE_MOVED,int,decl_cls)
add(:MOUSE_ENTERED,int,decl_cls)
add(:MOUSE_EXITED,int,decl_cls)
add(:MOUSE_DRAGGED,int,decl_cls)
add(:MOUSE_WHEEL,int,decl_cls)
add(:NOBUTTON,int,decl_cls)
add(:BUTTON1,int,decl_cls)
add(:BUTTON2,int,decl_cls)
add(:BUTTON3,int,decl_cls)
decl_cls = 'java.awt.event.MouseWheelEvent'
add(:WHEEL_UNIT_SCROLL,int,decl_cls)
add(:WHEEL_BLOCK_SCROLL,int,decl_cls)
decl_cls = 'java.awt.event.PaintEvent'
add(:PAINT_FIRST,int,decl_cls)
add(:PAINT_LAST,int,decl_cls)
add(:PAINT,int,decl_cls)
add(:UPDATE,int,decl_cls)
decl_cls = 'java.awt.event.TextEvent'
add(:TEXT_FIRST,int,decl_cls)
add(:TEXT_LAST,int,decl_cls)
add(:TEXT_VALUE_CHANGED,int,decl_cls)
decl_cls = 'java.awt.event.WindowEvent'
add(:WINDOW_FIRST,int,decl_cls)
add(:WINDOW_OPENED,int,decl_cls)
add(:WINDOW_CLOSING,int,decl_cls)
add(:WINDOW_CLOSED,int,decl_cls)
add(:WINDOW_ICONIFIED,int,decl_cls)
add(:WINDOW_DEICONIFIED,int,decl_cls)
add(:WINDOW_ACTIVATED,int,decl_cls)
add(:WINDOW_DEACTIVATED,int,decl_cls)
add(:WINDOW_GAINED_FOCUS,int,decl_cls)
add(:WINDOW_LOST_FOCUS,int,decl_cls)
add(:WINDOW_STATE_CHANGED,int,decl_cls)
add(:WINDOW_LAST,int,decl_cls)
decl_cls = 'java.awt.font.GlyphMetrics'
add(:STANDARD,byte,decl_cls)
add(:LIGATURE,byte,decl_cls)
add(:COMBINING,byte,decl_cls)
add(:COMPONENT,byte,decl_cls)
add(:WHITESPACE,byte,decl_cls)
decl_cls = 'java.awt.font.GlyphVector'
add(:FLAG_HAS_TRANSFORMS,int,decl_cls)
add(:FLAG_HAS_POSITION_ADJUSTMENTS,int,decl_cls)
add(:FLAG_RUN_RTL,int,decl_cls)
add(:FLAG_COMPLEX_GLYPHS,int,decl_cls)
add(:FLAG_MASK,int,decl_cls)
decl_cls = 'java.awt.font.GraphicAttribute'
add(:TOP_ALIGNMENT,int,decl_cls)
add(:BOTTOM_ALIGNMENT,int,decl_cls)
add(:ROMAN_BASELINE,int,decl_cls)
add(:CENTER_BASELINE,int,decl_cls)
add(:HANGING_BASELINE,int,decl_cls)
decl_cls = 'java.awt.font.NumericShaper'
add(:EUROPEAN,int,decl_cls)
add(:ARABIC,int,decl_cls)
add(:EASTERN_ARABIC,int,decl_cls)
add(:DEVANAGARI,int,decl_cls)
add(:BENGALI,int,decl_cls)
add(:GURMUKHI,int,decl_cls)
add(:GUJARATI,int,decl_cls)
add(:ORIYA,int,decl_cls)
add(:TAMIL,int,decl_cls)
add(:TELUGU,int,decl_cls)
add(:KANNADA,int,decl_cls)
add(:MALAYALAM,int,decl_cls)
add(:THAI,int,decl_cls)
add(:LAO,int,decl_cls)
add(:TIBETAN,int,decl_cls)
add(:MYANMAR,int,decl_cls)
add(:ETHIOPIC,int,decl_cls)
add(:KHMER,int,decl_cls)
add(:MONGOLIAN,int,decl_cls)
add(:ALL_RANGES,int,decl_cls)
decl_cls = 'java.awt.font.ShapeGraphicAttribute'
add(:STROKE,'boolean',decl_cls)
add(:FILL,'boolean',decl_cls)
add(:TOP_ALIGNMENT,int,decl_cls)
add(:BOTTOM_ALIGNMENT,int,decl_cls)
add(:ROMAN_BASELINE,int,decl_cls)
add(:CENTER_BASELINE,int,decl_cls)
add(:HANGING_BASELINE,int,decl_cls)
decl_cls = 'java.awt.font.TextAttribute'
add(:FAMILY,decl_cls,decl_cls)
add(:WEIGHT,decl_cls,decl_cls)
add(:WEIGHT_EXTRA_LIGHT,jfloat,decl_cls)
add(:WEIGHT_LIGHT,jfloat,decl_cls)
add(:WEIGHT_DEMILIGHT,jfloat,decl_cls)
add(:WEIGHT_REGULAR,jfloat,decl_cls)
add(:WEIGHT_SEMIBOLD,jfloat,decl_cls)
add(:WEIGHT_MEDIUM,jfloat,decl_cls)
add(:WEIGHT_DEMIBOLD,jfloat,decl_cls)
add(:WEIGHT_BOLD,jfloat,decl_cls)
add(:WEIGHT_HEAVY,jfloat,decl_cls)
add(:WEIGHT_EXTRABOLD,jfloat,decl_cls)
add(:WEIGHT_ULTRABOLD,jfloat,decl_cls)
add(:WIDTH,decl_cls,decl_cls)
add(:WIDTH_CONDENSED,jfloat,decl_cls)
add(:WIDTH_SEMI_CONDENSED,jfloat,decl_cls)
add(:WIDTH_REGULAR,jfloat,decl_cls)
add(:WIDTH_SEMI_EXTENDED,jfloat,decl_cls)
add(:WIDTH_EXTENDED,jfloat,decl_cls)
add(:POSTURE,decl_cls,decl_cls)
add(:POSTURE_REGULAR,jfloat,decl_cls)
add(:POSTURE_OBLIQUE,jfloat,decl_cls)
add(:SIZE,decl_cls,decl_cls)
add(:TRANSFORM,decl_cls,decl_cls)
add(:SUPERSCRIPT,decl_cls,decl_cls)
add(:SUPERSCRIPT_SUPER,integer,decl_cls)
add(:SUPERSCRIPT_SUB,integer,decl_cls)
add(:FONT,decl_cls,decl_cls)
add(:CHAR_REPLACEMENT,decl_cls,decl_cls)
add(:FOREGROUND,decl_cls,decl_cls)
add(:BACKGROUND,decl_cls,decl_cls)
add(:UNDERLINE,decl_cls,decl_cls)
add(:UNDERLINE_ON,integer,decl_cls)
add(:STRIKETHROUGH,decl_cls,decl_cls)
add(:STRIKETHROUGH_ON,jbool,decl_cls)
add(:RUN_DIRECTION,decl_cls,decl_cls)
add(:RUN_DIRECTION_LTR,jbool,decl_cls)
add(:RUN_DIRECTION_RTL,jbool,decl_cls)
add(:BIDI_EMBEDDING,decl_cls,decl_cls)
add(:JUSTIFICATION,decl_cls,decl_cls)
add(:JUSTIFICATION_FULL,jfloat,decl_cls)
add(:JUSTIFICATION_NONE,jfloat,decl_cls)
add(:INPUT_METHOD_HIGHLIGHT,decl_cls,decl_cls)
add(:INPUT_METHOD_UNDERLINE,decl_cls,decl_cls)
add(:UNDERLINE_LOW_ONE_PIXEL,integer,decl_cls)
add(:UNDERLINE_LOW_TWO_PIXEL,integer,decl_cls)
add(:UNDERLINE_LOW_DOTTED,integer,decl_cls)
add(:UNDERLINE_LOW_GRAY,integer,decl_cls)
add(:UNDERLINE_LOW_DASHED,integer,decl_cls)
add(:SWAP_COLORS,decl_cls,decl_cls)
add(:SWAP_COLORS_ON,jbool,decl_cls)
add(:NUMERIC_SHAPING,decl_cls,decl_cls)
add(:KERNING,decl_cls,decl_cls)
add(:KERNING_ON,integer,decl_cls)
add(:LIGATURES,decl_cls,decl_cls)
add(:LIGATURES_ON,integer,decl_cls)
add(:TRACKING,decl_cls,decl_cls)
add(:TRACKING_TIGHT,jfloat,decl_cls)
add(:TRACKING_LOOSE,jfloat,decl_cls)
add(:LANGUAGE,'java.text.AttributedCharacterIterator$Attribute',decl_cls)
add(:READING,'java.text.AttributedCharacterIterator$Attribute',decl_cls)
add(:INPUT_METHOD_SEGMENT,'java.text.AttributedCharacterIterator$Attribute',decl_cls)
decl_cls = 'java.awt.font.TransformAttribute'
add(:IDENTITY,decl_cls,decl_cls)
decl_cls = 'java.awt.geom.PathIterator'
add(:WIND_EVEN_ODD,int,decl_cls)
add(:WIND_NON_ZERO,int,decl_cls)
add(:SEG_MOVETO,int,decl_cls)
add(:SEG_LINETO,int,decl_cls)
add(:SEG_QUADTO,int,decl_cls)
add(:SEG_CUBICTO,int,decl_cls)
add(:SEG_CLOSE,int,decl_cls)
decl_cls = 'java.awt.geom.AffineTransform'
add(:TYPE_IDENTITY,int,decl_cls)
add(:TYPE_TRANSLATION,int,decl_cls)
add(:TYPE_UNIFORM_SCALE,int,decl_cls)
add(:TYPE_GENERAL_SCALE,int,decl_cls)
add(:TYPE_MASK_SCALE,int,decl_cls)
add(:TYPE_FLIP,int,decl_cls)
add(:TYPE_QUADRANT_ROTATION,int,decl_cls)
add(:TYPE_GENERAL_ROTATION,int,decl_cls)
add(:TYPE_MASK_ROTATION,int,decl_cls)
add(:TYPE_GENERAL_TRANSFORM,int,decl_cls)
decl_cls = 'java.awt.im.InputMethodHighlight'
add(:RAW_TEXT,int,decl_cls)
add(:CONVERTED_TEXT,int,decl_cls)
add(:UNSELECTED_RAW_TEXT_HIGHLIGHT,decl_cls,decl_cls)
add(:SELECTED_RAW_TEXT_HIGHLIGHT,decl_cls,decl_cls)
add(:UNSELECTED_CONVERTED_TEXT_HIGHLIGHT,decl_cls,decl_cls)
add(:SELECTED_CONVERTED_TEXT_HIGHLIGHT,decl_cls,decl_cls)
decl_cls = 'java.awt.image.AffineTransformOp'
add(:TYPE_NEAREST_NEIGHBOR,int,decl_cls)
add(:TYPE_BILINEAR,int,decl_cls)
add(:TYPE_BICUBIC,int,decl_cls)
decl_cls = 'java.awt.image.BufferedImage'
add(:TYPE_CUSTOM,int,decl_cls)
add(:TYPE_INT_RGB,int,decl_cls)
add(:TYPE_INT_ARGB,int,decl_cls)
add(:TYPE_INT_ARGB_PRE,int,decl_cls)
add(:TYPE_INT_BGR,int,decl_cls)
add(:TYPE_3BYTE_BGR,int,decl_cls)
add(:TYPE_4BYTE_ABGR,int,decl_cls)
add(:TYPE_4BYTE_ABGR_PRE,int,decl_cls)
add(:TYPE_USHORT_565_RGB,int,decl_cls)
add(:TYPE_USHORT_555_RGB,int,decl_cls)
add(:TYPE_BYTE_GRAY,int,decl_cls)
add(:TYPE_USHORT_GRAY,int,decl_cls)
add(:TYPE_BYTE_BINARY,int,decl_cls)
add(:TYPE_BYTE_INDEXED,int,decl_cls)
add(:OPAQUE,int,decl_cls)
add(:BITMASK,int,decl_cls)
add(:TRANSLUCENT,int,decl_cls)
add(:UndefinedProperty,object,decl_cls)
add(:SCALE_DEFAULT,int,decl_cls)
add(:SCALE_FAST,int,decl_cls)
add(:SCALE_SMOOTH,int,decl_cls)
add(:SCALE_REPLICATE,int,decl_cls)
add(:SCALE_AREA_AVERAGING,int,decl_cls)
decl_cls = 'java.awt.image.ConvolveOp'
add(:EDGE_ZERO_FILL,int,decl_cls)
add(:EDGE_NO_OP,int,decl_cls)
decl_cls = 'java.awt.image.DataBuffer'
add(:TYPE_BYTE,int,decl_cls)
add(:TYPE_USHORT,int,decl_cls)
add(:TYPE_SHORT,int,decl_cls)
add(:TYPE_INT,int,decl_cls)
add(:TYPE_FLOAT,int,decl_cls)
add(:TYPE_DOUBLE,int,decl_cls)
add(:TYPE_UNDEFINED,int,decl_cls)
decl_cls = 'java.awt.image.ImageConsumer'
add(:RANDOMPIXELORDER,int,decl_cls)
add(:TOPDOWNLEFTRIGHT,int,decl_cls)
add(:COMPLETESCANLINES,int,decl_cls)
add(:SINGLEPASS,int,decl_cls)
add(:SINGLEFRAME,int,decl_cls)
add(:IMAGEERROR,int,decl_cls)
add(:SINGLEFRAMEDONE,int,decl_cls)
add(:STATICIMAGEDONE,int,decl_cls)
add(:IMAGEABORTED,int,decl_cls)
decl_cls = 'java.awt.image.VolatileImage'
add(:IMAGE_OK,int,decl_cls)
add(:IMAGE_RESTORED,int,decl_cls)
add(:IMAGE_INCOMPATIBLE,int,decl_cls)
add(:OPAQUE,int,decl_cls)
add(:BITMASK,int,decl_cls)
add(:TRANSLUCENT,int,decl_cls)
add(:UndefinedProperty,object,decl_cls)
add(:SCALE_DEFAULT,int,decl_cls)
add(:SCALE_FAST,int,decl_cls)
add(:SCALE_SMOOTH,int,decl_cls)
add(:SCALE_REPLICATE,int,decl_cls)
add(:SCALE_AREA_AVERAGING,int,decl_cls)
decl_cls = 'java.awt.image.renderable.RenderableImage'
add(:HINTS_OBSERVED,string,decl_cls)
decl_cls = 'java.awt.print.Pageable'
add(:UNKNOWN_NUMBER_OF_PAGES,int,decl_cls)
decl_cls = 'java.awt.print.Printable'
add(:PAGE_EXISTS,int,decl_cls)
add(:NO_SUCH_PAGE,int,decl_cls)
decl_cls = 'java.awt.print.PageFormat'
add(:LANDSCAPE,int,decl_cls)
add(:PORTRAIT,int,decl_cls)
add(:REVERSE_LANDSCAPE,int,decl_cls)
end #Constants
end #AWT
end #Cheri
